[package]
name = "web-scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.28"
scraper = "0.25.0"
tokio ={ version= "1.48.0", features = ["full"] }
openssl = { version = "0.10", features = ["vendored"] }

