[package]
name = "olympus_manwha"
version = "0.1.0"
edition = "2024"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
reqwest = {version = "0.13", features = [ "blocking"]}
scraper = "0.25.0"

dirs = "6.0"

